{{- range .Values.postgresClusters }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "postgres" }}
  {{- with .labels }}
  labels:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
{{ toYaml .spec | indent 2 }}
{{- end }}
