{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
{{- with .labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
provisioner: {{ .provisioner }}
{{- with .reclaimPolicy }}
reclaimPolicy: {{ . }}
{{- end }}
{{- with .volumeBindingMode }}
volumeBindingMode: {{ . }}
{{- end }}
{{- if hasKey . "allowVolumeExpansion" }}
allowVolumeExpansion: {{ .allowVolumeExpansion }}
{{- end }}
{{- with .mountOptions }}
mountOptions:
{{ toYaml . | indent 2 }}
{{- end }}
{{- with .allowedTopologies }}
allowedTopologies:
{{ toYaml . | indent 2 }}
{{- end }}
{{- with .parameters }}
parameters:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
